largura1 = float (input ('Qual a largura do primeiro cômodo: '))
comprimento1 = float (input ('Qual o comprimento do primeiro cômodo: '))
comodo1 =(largura1*comprimento1)
largura2 = float (input ('Qual a largura do segundo cômodo: '))
comprimento2 = float (input ('Qual o comprimento do segundo cômodo: '))
comodo2 = (largura2*comprimento2)
largura3 = float (input ('Qual a largura do terceiro cômodo: '))
comprimento3 = float (input ('Qual o comprimento do terceiro cômodo: '))
comodo3 = (largura3*comprimento3)
largura4 = float (input ('Qual a largura do quarto cômodo: '))
comprimento4 = float (input ('Qual o comprimento do quarto cômodo: '))
comodo4 = (largura4*comprimento4)
m2casa = float(comodo1+comodo2+comodo3+comodo4)
print (' A sua casa mede {:.2f}'.format(m2casa) ,'m².')
